title: YI 2022 Workshops
author: Childhood Cancer Data Lab
email: training@ccdatalab.org
twitter_username: CancerDataLab
github_username:  AlexsLemonade
# Theme and theme options
theme: minima
# Pages to appear in site header.
header_home:
  HOME.md
header_pages:
  - participant-information.md
  - reproducibility-resources.md
  - intro_r/index.md
  - rrp/index.md



